version: 0.2
env:
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub-username-secret
    DOCKERHUB_PASSWORD: dockerhub-password-secret
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 287925497349.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=287925497349.dkr.ecr.ap-southeast-1.amazonaws.com/codebuild-nodejs-random-color
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nodejs-random-color .
      - docker tag nodejs-random-color:latest $REPOSITORY_URI:latest
      - docker tag nodejs-random-color:latest $REPOSITORY_URI:$COMMIT_HASH

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - echo Build completed on `date`
      - echo Writing image definitions file...
      - printf '[{"name":"nodejs-container","imageUri":"%s"}]'
        $REPOSITORY_URI:$COMMIT_HASH > imagedefinitions.json # danh sách container, nếu ta tạo ra một file mà mảng có nhiều container thì nó sẽ triển khai taonf bộ danh sách container đó lên service
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
# Câu lệnh này sẽ tạo ra một tệp imagedefinitions.json với nội dung như sau (giả sử các giá trị của biến):
# [{"name":"nodejs-container","imageUri":"123456789012.dkr.ecr.us-west-2.amazonaws.com/my-repo:abcd1234"}]
